apiVersion: 1
contactPoints:
  - orgId: 1
    name: incident-responder
    receivers:
      - uid: incident-responder-webhook
        type: webhook
        settings:
          url: http://incident-response:8001/alerts
          httpMethod: POST
        disableResolveMessage: false
policies:
  - orgId: 1
    receiver: incident-responder
    group_by: [grafana_folder, alertname]
